var annotated_dup =
[
    [ "cen", "namespacecen.html", [
      [ "experimental", "namespacecen_1_1experimental.html", [
        [ "font_bundle", "classcen_1_1experimental_1_1font__bundle.html", "classcen_1_1experimental_1_1font__bundle" ]
      ] ],
      [ "audio_device_event", "classcen_1_1audio__device__event.html", "classcen_1_1audio__device__event" ],
      [ "ball_axis_delta", "structcen_1_1ball__axis__delta.html", "structcen_1_1ball__axis__delta" ],
      [ "basic_area", "structcen_1_1basic__area.html", "structcen_1_1basic__area" ],
      [ "basic_controller", "classcen_1_1basic__controller.html", "classcen_1_1basic__controller" ],
      [ "basic_cursor", "classcen_1_1basic__cursor.html", "classcen_1_1basic__cursor" ],
      [ "basic_gl_context", "classcen_1_1basic__gl__context.html", "classcen_1_1basic__gl__context" ],
      [ "basic_joystick", "classcen_1_1basic__joystick.html", "classcen_1_1basic__joystick" ],
      [ "basic_pixel_format_info", "classcen_1_1basic__pixel__format__info.html", "classcen_1_1basic__pixel__format__info" ],
      [ "basic_point", "classcen_1_1basic__point.html", "classcen_1_1basic__point" ],
      [ "basic_rect", "classcen_1_1basic__rect.html", "classcen_1_1basic__rect" ],
      [ "basic_renderer", "classcen_1_1basic__renderer.html", "classcen_1_1basic__renderer" ],
      [ "basic_sensor", "classcen_1_1basic__sensor.html", "classcen_1_1basic__sensor" ],
      [ "basic_sound_effect", "classcen_1_1basic__sound__effect.html", null ],
      [ "basic_surface", "classcen_1_1basic__surface.html", "classcen_1_1basic__surface" ],
      [ "basic_texture", "classcen_1_1basic__texture.html", "classcen_1_1basic__texture" ],
      [ "basic_vector3", "structcen_1_1basic__vector3.html", "structcen_1_1basic__vector3" ],
      [ "basic_window", "classcen_1_1basic__window.html", "classcen_1_1basic__window" ],
      [ "blend_task", "structcen_1_1blend__task.html", "structcen_1_1blend__task" ],
      [ "color", "classcen_1_1color.html", "classcen_1_1color" ],
      [ "condition", "classcen_1_1condition.html", "classcen_1_1condition" ],
      [ "controller_axis_event", "classcen_1_1controller__axis__event.html", "classcen_1_1controller__axis__event" ],
      [ "controller_button_event", "classcen_1_1controller__button__event.html", "classcen_1_1controller__button__event" ],
      [ "controller_device_event", "classcen_1_1controller__device__event.html", "classcen_1_1controller__device__event" ],
      [ "controller_finger_state", "structcen_1_1controller__finger__state.html", "structcen_1_1controller__finger__state" ],
      [ "controller_sensor_event", "classcen_1_1controller__sensor__event.html", "classcen_1_1controller__sensor__event" ],
      [ "controller_touchpad_event", "classcen_1_1controller__touchpad__event.html", "classcen_1_1controller__touchpad__event" ],
      [ "deleter", "structcen_1_1deleter.html", null ],
      [ "deleter< Mix_Chunk >", "structcen_1_1deleter_3_01_mix___chunk_01_4.html", "structcen_1_1deleter_3_01_mix___chunk_01_4" ],
      [ "deleter< Mix_Music >", "structcen_1_1deleter_3_01_mix___music_01_4.html", "structcen_1_1deleter_3_01_mix___music_01_4" ],
      [ "deleter< SDL_cond >", "structcen_1_1deleter_3_01_s_d_l__cond_01_4.html", "structcen_1_1deleter_3_01_s_d_l__cond_01_4" ],
      [ "deleter< SDL_Cursor >", "structcen_1_1deleter_3_01_s_d_l___cursor_01_4.html", "structcen_1_1deleter_3_01_s_d_l___cursor_01_4" ],
      [ "deleter< SDL_GameController >", "structcen_1_1deleter_3_01_s_d_l___game_controller_01_4.html", "structcen_1_1deleter_3_01_s_d_l___game_controller_01_4" ],
      [ "deleter< SDL_Haptic >", "structcen_1_1deleter_3_01_s_d_l___haptic_01_4.html", "structcen_1_1deleter_3_01_s_d_l___haptic_01_4" ],
      [ "deleter< SDL_Joystick >", "structcen_1_1deleter_3_01_s_d_l___joystick_01_4.html", "structcen_1_1deleter_3_01_s_d_l___joystick_01_4" ],
      [ "deleter< SDL_mutex >", "structcen_1_1deleter_3_01_s_d_l__mutex_01_4.html", "structcen_1_1deleter_3_01_s_d_l__mutex_01_4" ],
      [ "deleter< SDL_Palette >", "structcen_1_1deleter_3_01_s_d_l___palette_01_4.html", "structcen_1_1deleter_3_01_s_d_l___palette_01_4" ],
      [ "deleter< SDL_PixelFormat >", "structcen_1_1deleter_3_01_s_d_l___pixel_format_01_4.html", "structcen_1_1deleter_3_01_s_d_l___pixel_format_01_4" ],
      [ "deleter< SDL_Renderer >", "structcen_1_1deleter_3_01_s_d_l___renderer_01_4.html", "structcen_1_1deleter_3_01_s_d_l___renderer_01_4" ],
      [ "deleter< SDL_RWops >", "structcen_1_1deleter_3_01_s_d_l___r_wops_01_4.html", "structcen_1_1deleter_3_01_s_d_l___r_wops_01_4" ],
      [ "deleter< SDL_sem >", "structcen_1_1deleter_3_01_s_d_l__sem_01_4.html", "structcen_1_1deleter_3_01_s_d_l__sem_01_4" ],
      [ "deleter< SDL_Sensor >", "structcen_1_1deleter_3_01_s_d_l___sensor_01_4.html", "structcen_1_1deleter_3_01_s_d_l___sensor_01_4" ],
      [ "deleter< SDL_Surface >", "structcen_1_1deleter_3_01_s_d_l___surface_01_4.html", "structcen_1_1deleter_3_01_s_d_l___surface_01_4" ],
      [ "deleter< SDL_Texture >", "structcen_1_1deleter_3_01_s_d_l___texture_01_4.html", "structcen_1_1deleter_3_01_s_d_l___texture_01_4" ],
      [ "deleter< SDL_Window >", "structcen_1_1deleter_3_01_s_d_l___window_01_4.html", "structcen_1_1deleter_3_01_s_d_l___window_01_4" ],
      [ "deleter< TTF_Font >", "structcen_1_1deleter_3_01_t_t_f___font_01_4.html", "structcen_1_1deleter_3_01_t_t_f___font_01_4" ],
      [ "display_event", "classcen_1_1display__event.html", "classcen_1_1display__event" ],
      [ "display_mode", "classcen_1_1display__mode.html", "classcen_1_1display__mode" ],
      [ "dollar_gesture_event", "classcen_1_1dollar__gesture__event.html", "classcen_1_1dollar__gesture__event" ],
      [ "dpi_info", "structcen_1_1dpi__info.html", "structcen_1_1dpi__info" ],
      [ "drop_event", "classcen_1_1drop__event.html", "classcen_1_1drop__event" ],
      [ "event_base", "classcen_1_1event__base.html", "classcen_1_1event__base" ],
      [ "event_dispatcher", "classcen_1_1event__dispatcher.html", "classcen_1_1event__dispatcher" ],
      [ "event_handler", "classcen_1_1event__handler.html", "classcen_1_1event__handler" ],
      [ "event_sink", "classcen_1_1event__sink.html", "classcen_1_1event__sink" ],
      [ "exception", "classcen_1_1exception.html", "classcen_1_1exception" ],
      [ "file", "classcen_1_1file.html", "classcen_1_1file" ],
      [ "finger", "classcen_1_1finger.html", "classcen_1_1finger" ],
      [ "font", "classcen_1_1font.html", "classcen_1_1font" ],
      [ "font_cache", "classcen_1_1font__cache.html", "classcen_1_1font__cache" ],
      [ "font_dpi", "structcen_1_1font__dpi.html", "structcen_1_1font__dpi" ],
      [ "gl_library", "classcen_1_1gl__library.html", "classcen_1_1gl__library" ],
      [ "glyph_metrics", "structcen_1_1glyph__metrics.html", "structcen_1_1glyph__metrics" ],
      [ "img", "classcen_1_1img.html", "classcen_1_1img" ],
      [ "img_cfg", "structcen_1_1img__cfg.html", "structcen_1_1img__cfg" ],
      [ "img_error", "classcen_1_1img__error.html", "classcen_1_1img__error" ],
      [ "joy_axis_event", "classcen_1_1joy__axis__event.html", "classcen_1_1joy__axis__event" ],
      [ "joy_ball_event", "classcen_1_1joy__ball__event.html", "classcen_1_1joy__ball__event" ],
      [ "joy_button_event", "classcen_1_1joy__button__event.html", "classcen_1_1joy__button__event" ],
      [ "joy_device_event", "classcen_1_1joy__device__event.html", "classcen_1_1joy__device__event" ],
      [ "joy_hat_event", "classcen_1_1joy__hat__event.html", "classcen_1_1joy__hat__event" ],
      [ "key_code", "classcen_1_1key__code.html", "classcen_1_1key__code" ],
      [ "keyboard", "classcen_1_1keyboard.html", "classcen_1_1keyboard" ],
      [ "keyboard_event", "classcen_1_1keyboard__event.html", "classcen_1_1keyboard__event" ],
      [ "locale", "classcen_1_1locale.html", "classcen_1_1locale" ],
      [ "message_box", "classcen_1_1message__box.html", "classcen_1_1message__box" ],
      [ "message_box_color_scheme", "classcen_1_1message__box__color__scheme.html", "classcen_1_1message__box__color__scheme" ],
      [ "mix", "classcen_1_1mix.html", "classcen_1_1mix" ],
      [ "mix_cfg", "structcen_1_1mix__cfg.html", "structcen_1_1mix__cfg" ],
      [ "mix_error", "classcen_1_1mix__error.html", "classcen_1_1mix__error" ],
      [ "mouse", "classcen_1_1mouse.html", "classcen_1_1mouse" ],
      [ "mouse_button_event", "classcen_1_1mouse__button__event.html", "classcen_1_1mouse__button__event" ],
      [ "mouse_motion_event", "classcen_1_1mouse__motion__event.html", "classcen_1_1mouse__motion__event" ],
      [ "mouse_wheel_event", "classcen_1_1mouse__wheel__event.html", "classcen_1_1mouse__wheel__event" ],
      [ "multi_gesture_event", "classcen_1_1multi__gesture__event.html", "classcen_1_1multi__gesture__event" ],
      [ "mutex", "classcen_1_1mutex.html", "classcen_1_1mutex" ],
      [ "palette", "classcen_1_1palette.html", "classcen_1_1palette" ],
      [ "point_traits", "classcen_1_1point__traits.html", "classcen_1_1point__traits" ],
      [ "quit_event", "classcen_1_1quit__event.html", "classcen_1_1quit__event" ],
      [ "rect_traits", "classcen_1_1rect__traits.html", "classcen_1_1rect__traits" ],
      [ "renderer_info", "classcen_1_1renderer__info.html", "classcen_1_1renderer__info" ],
      [ "renderer_scale", "structcen_1_1renderer__scale.html", "structcen_1_1renderer__scale" ],
      [ "result", "classcen_1_1result.html", "classcen_1_1result" ],
      [ "scan_code", "classcen_1_1scan__code.html", "classcen_1_1scan__code" ],
      [ "scoped_lock", "classcen_1_1scoped__lock.html", "classcen_1_1scoped__lock" ],
      [ "sdl", "classcen_1_1sdl.html", "classcen_1_1sdl" ],
      [ "sdl_cfg", "structcen_1_1sdl__cfg.html", "structcen_1_1sdl__cfg" ],
      [ "sdl_error", "classcen_1_1sdl__error.html", "classcen_1_1sdl__error" ],
      [ "sdl_string", "classcen_1_1sdl__string.html", "classcen_1_1sdl__string" ],
      [ "semaphore", "classcen_1_1semaphore.html", "classcen_1_1semaphore" ],
      [ "sensor_event", "classcen_1_1sensor__event.html", "classcen_1_1sensor__event" ],
      [ "shared_object", "classcen_1_1shared__object.html", "classcen_1_1shared__object" ],
      [ "simd_block", "classcen_1_1simd__block.html", "classcen_1_1simd__block" ],
      [ "text_editing_event", "classcen_1_1text__editing__event.html", "classcen_1_1text__editing__event" ],
      [ "text_input_event", "classcen_1_1text__input__event.html", "classcen_1_1text__input__event" ],
      [ "thread", "classcen_1_1thread.html", "classcen_1_1thread" ],
      [ "touch_finger_event", "classcen_1_1touch__finger__event.html", "classcen_1_1touch__finger__event" ],
      [ "try_lock", "classcen_1_1try__lock.html", "classcen_1_1try__lock" ],
      [ "ttf", "classcen_1_1ttf.html", "classcen_1_1ttf" ],
      [ "ttf_error", "classcen_1_1ttf__error.html", "classcen_1_1ttf__error" ],
      [ "unicode_string", "classcen_1_1unicode__string.html", "classcen_1_1unicode__string" ],
      [ "user_event", "classcen_1_1user__event.html", "classcen_1_1user__event" ],
      [ "vk_library", "classcen_1_1vk__library.html", "classcen_1_1vk__library" ],
      [ "window_event", "classcen_1_1window__event.html", "classcen_1_1window__event" ]
    ] ]
];